---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-init
  namespace: "kaapana-system-{{  .Values.global.instance_id  }}"
spec:
  template:
    metadata:
      name: cert-init
    spec:
      containers:
      - name: cert-init
        image: "{{ .Values.global.registry_url }}/cert-init:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_jobs }}
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 200Mi
        env:
        - name: ACTION
          value: "install"
        - name: SECRET_NAME
          value: "{{ .Values.global.tls_secret.name }}"
        - name: SECRET_NAMESPACE
          value: "kaapana-system-{{  .Values.global.instance_id  }}"
        - name: COMMON_NAME
          value: "{{ .Values.global.tls_secret.common_name }}"
        - name: EXPIRATION
          value: "{{ .Values.global.tls_secret.expiration }}"
        volumeMounts:
        - name: tls-storage
          mountPath: /cert/tls
      volumes:
      - name: tls-storage
        hostPath:
          path: "{{ .Values.global.fast_data_dir }}/tls"
          type: DirectoryOrCreate
      restartPolicy: Never
      serviceAccountName: kubernetes-dashboard
      imagePullSecrets:
      - name: registry-secret