---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaapana-backend
  namespace: {{ .Values.global.base_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: kaapana-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app-name: kaapana-backend
    spec:
      initContainers:
        - name: init-wait-for-postgres
          image: "{{ .Values.global.registry_url }}/service-checker:{{ .Values.global.kaapana_build_version }}"
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          env:
            - name: WAIT
              value: "kaapana-backend-postgres,kaapana-backend-postgres-service.base.svc,5432"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
        - name: init-wait-for-keycloak
          image: "{{ .Values.global.registry_url }}/service-checker:{{ .Values.global.kaapana_build_version }}"
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          env:
            - name: WAIT
              value: "keycloak,keycloak-internal-service.kub-system-{{  .Values.global.instance_id  }}.svc,443"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
        - name: init-create-backend-user
          image: "{{ .Values.global.registry_url }}/kaapana-backend:{{ .Values.global.kaapana_build_version }}"
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          command: ["/app/scripts/create_backend_user.py"]
          env:
            - name: KEYCLOAK_URL
              value: {{ .Values.global.keycloak_url }}
            - name: KEYCLOAK_ADMIN_USERNAME
              value: {{ .Values.global.credentials_keycloak_admin_username }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.global.credentials_keycloak_admin_password }}
            - name: KEYCLOAK_BACKEND_USERNAME
              value: {{ .Values.global.credentials_keycloak_backend_user }}
            - name: KEYCLOAK_BACKEND_PASSWORD
              value: {{ .Values.global.credentials_keycloak_backend_password }}
            - name: KEYCLOAK_BACKEND_ROLES
              value: "query-groups;query-users;view-users"
      containers:
      - name: kaapana-backend
        image: "{{ .Values.global.registry_url }}/kaapana-backend:{{ .Values.global.kaapana_build_version }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        # command: ["tail"]
        # args: ["-f", "/dev/null"] 
        command: ["/bin/sh"]
        args: ["/app/boot.sh"] 
        env: # Environment variables
        - name: SECRET_KEY
          value: kaapana-secret
        - name: INSTANCE_NAME
          value: {{ .Values.global.instance_name | default "central" }}
        - name: INSTANCE_ID
          value: "{{ .Values.global.instance_id }}"
        - name: HOSTNAME
          value: {{ .Values.global.hostname | default "" }}
        - name: HTTPS_PORT
          value: "{{ .Values.global.https_port }}"
        - name: http_proxy
          value: {{ .Values.global.http_proxy }}
        - name: https_proxy
          value: {{ .Values.global.http_proxy }}
        - name: no_proxy
          value: "kaapana-backend-postgres-service.base,kaapana-backend-postgres-service.base.svc,airflow-service.flow,airflow-service.flow.svc,minio-service.store,minio-service.store.svc,opensearch-service.meta,opensearch-service.meta.svc"
        - name: KUBE_HELM_URL
          value: "http://kube-helm-service.kub-system-{{  .Values.global.instance_id  }}.svc:5000/kube-helm-api"
        - name: PROMETHEUS_URL
          value: {{ .Values.global.prometheus_url }}
        - name: KEYCLOAK_URL
          value: {{ .Values.global.keycloak_url }}
        - name: MINIO_USERNAME
          value: {{ .Values.global.credentials_minio_username  | default "" }}
        - name: MINIO_PASSWORD
          value: {{ .Values.global.credentials_minio_password | default ""}}
        - name: MINIO_URL
          value: {{ .Values.global.minio_url }}
        - name: APPLICATION_ROOT
          value: "/kaapana-backend"
        - name: DATABASE_URL
          value: postgresql://kaapanauser:kaapanapassword@kaapana-backend-postgres-service.base.svc:5432
        - name: REMOTE_SYNC_INTERVAL
          value: "5"
        - name: KEYCLOAK_ADMIN_USERNAME
          value: {{ .Values.global.credentials_keycloak_admin_username }}
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: {{ .Values.global.credentials_keycloak_admin_password }}
        - name: KEYCLOAK_BACKEND_USERNAME
          value: {{ .Values.global.credentials_keycloak_backend_user }}
        - name: KEYCLOAK_BACKEND_PASSWORD
          value: {{ .Values.global.credentials_keycloak_backend_password }}
        ports:
          - containerPort: 5000
        resources:
          limits:
            memory: "5Gi"
          requests:
            memory: "100Mi"
        volumeMounts:
{{- if .Values.global.dev_files }}
        - name: kaapana-dev-files
          mountPath: /app
{{- end }}
        - name: alembic
          mountPath: /app/alembic
      imagePullSecrets:
        - name: registry-secret
      volumes:
      - name: alembic
        hostPath:
          # path: /home/ubuntu/dev/kaapana-backend/docker/files
          path: /home/kaapana/alembic-kaapana-backend
          type: DirectoryOrCreate
{{- if .Values.global.dev_files }}
      - name: kaapana-dev-files
        hostPath:
          path: {{ .Values.global.dev_files}}
          type: DirectoryOrCreate
{{- end }}
---