---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
  namespace: "kub-system-{{  .Values.global.instance_id  }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: postgres-keycloak
  template:
    metadata:
      labels:
        app-name: postgres-keycloak
    spec:
      containers:
        - name: postgres-keycloak-container
          image: "{{ .Values.global.registry_url }}/postgres-9.5-alpine:{{ .Values.global.kaapana_build_version  }}"
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          env:
            - name: PGDATA
              value: "/db/db-files/"
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 500Mi
          volumeMounts:
            - mountPath: /db
              name: postgresdata
            # - name: postgres-keycloak-config-file
            #   mountPath: /docker-entrypoint-initdb.d/keycloak.sql
            #   subPath: keycloak.sql
      volumes:
      # - name: postgres-keycloak-config-file
      #   configMap:
      #     name: postgres-keycloak-config
      #     items:
      #     - key: keycloak.sql
      #       path: keycloak.sql
      - name: postgresdata
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/postgres-keycloak
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
