---
- hosts: localhost
  gather_facts: no
  vars:
    - target: "{{ target_host }}"
      default: "10.128.128.218"
  tasks:
    - add_host:
        name: "{{ target }}"
        groups: os_server

- name: Install Kaapana platform on server
  hosts: os_server
  strategy: free
  remote_user: "{{ remote_username }}"
  vars:
    #TODO: change hardcoded
    ansible_ssh_private_key_file: ~/.ssh/kaapana.pem
  tasks:
    - name: Copy data
      become: yes
      copy:
        src: "/app/install_platform.sh"
        dest: "/home/ubuntu/install_platform.sh"
        mode: '0777'
      #delegate_to: 127.0.0.1
    - name: Run the script
      become: no
      become_user: ubuntu
      environment:
        TERM: xterm
      shell: ./install_platform.sh --quiet --username {{ registry_user }} --password {{ registry_pwd }}
      args:
        chdir: /home/ubuntu/
      #script: /home/ubuntu/install_platform.sh --quiet --username {{ registry_user }} --password {{ registry_pwd }}
    - name: for debugging
      debug:
        msg: " Debugging Task Execution: Platform Installation Script Called..."