---
- hosts: localhost
  gather_facts: no
  vars:
    - target: "{{ target_host }}"
      default: "10.128.128.218"
  tasks:
    - add_host:
        name: "{{ target }}"
        groups: os_server

- name: Install Kaapana platform on server
  hosts: os_server
  strategy: free
  remote_user: "{{ remote_username }}"
  vars:
    #TODO: change hardcoded
    ansible_ssh_private_key_file: ~/.ssh/kaapana.pem
  tasks:
    - name: Set platform installation script path
      #debugger: on_failed
      set_fact: 
        #script_path: "{{ lookup('env','HOME') }}/kaapana/platforms/kaapana-platform/platform-installation"
        #script_path: "/home/ubuntu/kaapana/platforms/kaapana-platform/platform-installation"
        script_path: /tmp/
    - name: download the file
      become: no
      become_user: ubuntu
      command: wget https://raw.githubusercontent.com/kaapana/kaapana/feature/tfdamvp1/platforms/kaapana-platform/platform-installation/install_platform.sh
    - name: add permission
      become: no
      become_user: ubuntu
      command: chmod +x install_platform.sh
    - name: execute it
      become: no
      become_user: ubuntu
      command: ./install_platform.sh  --username tfdamvp1 --password 2vHU4y1_5iS1TzeLAif9
