apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: "kaapana-system-{{  .Values.global.instance_id  }}"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: websecure
      port: {{ .Values.global.https_port }}
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-http
  namespace: "kaapana-system-{{  .Values.global.instance_id  }}"
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: {{ .Values.global.http_port }}
      nodePort: {{ .Values.global.http_port }}
  selector:
    app: traefik
---
