---
dependencies:
  - name: base
    version: 0.0.0
    repository: file://deps/base
  - name: flow
    version: 0.0.0
    repository: file://deps/flow
  - name: meta
    version: 0.0.0
    repository: file://deps/meta
  - name: monitoring
    version: 0.0.0
    repository: file://deps/monitoring
  - name: store
    version: 0.0.0
    repository: file://deps/store
  - name: error-pages-chart
    version: 0.0.0
    repository: file://../../services/kaapana-core/error-pages/error-pages-chart
  - name: oAuth2-proxy-chart
    version: 0.0.0
    repository: file://../../services/kaapana-core/oAuth2-proxy/oAuth2-proxy-chart
  - name: keycloak-chart
    version: 0.0.0
    repository: file://../../services/kaapana-core/keycloak/keycloak-chart
  - name: traefik-chart
    version: 0.0.0
    repository: file://../../services/kaapana-core/traefik/traefik-chart
  - name: kube-dashboard-chart
    version: 0.0.0
    repository: file://../../services/kaapana-core/kubernetes-dashboard/kube-dashboard-chart
  - name: kube-helm-chart
    version: 0.0.0
    repository: file://../../services/kaapana-core/kube-helm/kube-helm-chart
  - name: cert-init-chart
    version: 0.0.0
    repository: file://../../services/kaapana-core/core-init/cert-init/cert-init-chart
  