---
dependencies:
  - name: error-pages-chart
    version: 0.0.0
  - name: keycloak-chart
    version: 0.0.0
  - name: kube-dashboard-chart
    version: 0.0.0
  - name: cert-init-chart
    version: 0.0.0
