---
apiVersion: v1
kind: Service
metadata:
  name: elastic-logging-service
  namespace: {{ .Values.global.monitoring_namespace }}
  labels:
    app-name: elastic-logging
spec:
  selector:
    app-name: elastic-logging
  type: ClusterIP
  ports:
  - name: elastic-log
    port: 9200
    targetPort: 9200
    protocol: TCP
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: elasticsearch-logging-ingress
#   namespace: {{ .Values.global.monitoring_namespace }}
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,kube-system-strip-prefix@kubernetescrd
#     kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
# spec:
#   rules:
#   - host:
#     http:
#       paths:
#       - path: /elastic-logging
#         backend:
#           serviceName: elastic-logging-service
#           servicePort: elastic-log
#---