apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-webserver-config
  namespace: {{ .Values.global.flow_namespace }}
data:
   webserver_config.py: |+
    #
    # Licensed to the Apache Software Foundation (ASF) under one
    # or more contributor license agreements.  See the NOTICE file
    # distributed with this work for additional information
    # regarding copyright ownership.  The ASF licenses this file
    # to you under the Apache License, Version 2.0 (the
    # "License"); you may not use this file except in compliance
    # with the License.  You may obtain a copy of the License at
    #
    #   http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicableapiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-webserver-config
  namespace: {{ .Values.global.flow_namespace }}
data:
   webserver_config.py: |+
    AUTH_TYPE = AUTH_DB

    # Uncomment to setup Full admin role name
    AUTH_ROLE_ADMIN = 'Admin'

    # Uncomment to setup Public role name, no authentication needed
    AUTH_ROLE_PUBLIC = 'Admin'