---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-de
  namespace: {{ .Values.global.meta_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: opensearch
  template:
    metadata:
      labels:
        app-name: opensearch
    spec:
      initContainers:
          - name: volume-permissions
            image: {{ .Values.global.registry_url }}/busybox:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__1.31
            imagePullPolicy:  IfNotPresent
            command: ["sh", "-c", "chown -R 1000:1000 /os_data && chown -R 1000:1000 /os_logs"]
            # command: ["sh", "-c", "chown -R 1000:1000 /os_data && chown -R 1000:1000 /os_logs && cp /os_ssl/* /os_config && chown -R 1000:1000 /os_config"]
            volumeMounts:
            - mountPath: /os_data
              name: osdata
            - mountPath: /os_logs
              name: oslogs
      containers:
        - name: opensearch-container
          image: {{ .Values.global.registry_url }}/opensearch:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__2.2.0
          imagePullPolicy: {{ .Values.global.pull_policy_pods }}
          env:
          - name: plugins.security.disabled
            value: "true"
          - name: DISABLE_INSTALL_DEMO_CONFIG
            value: "true"
          - name: cluster.name
            value: "opensearch-cluster"
          - name: node.name
            value: "os-node1"
          - name: discovery.seed_hosts
            value: "os-node1"
          - name: cluster.initial_cluster_manager_nodes
            value: "os-node1"
          - name: OPENSEARCH_JAVA_OPTS
            value: '-Xms512m -Xmx512m'
          resources:
            requests:
              memory: 500Mi
            limits:
              memory: 1000Mi
          volumeMounts:
            - name: osdata
              mountPath: /usr/share/opensearch/data
            - name: oslogs
              mountPath: /usr/share/opensearch/logs
            - name: sec-config
              mountPath: plugins/opensearch-security/securityconfig/config.yml
              subPath: config.yml
      volumes:
      - name: osdata
        hostPath:
          path: {{ .Values.global.fast_data_dir | default "/home/kaapana" }}/opensearch-data
          type: DirectoryOrCreate
      - name: oslogs
        hostPath:
          path: {{ .Values.global.fast_data_dir | default "/home/kaapana" }}/opensearch-logs
          type: DirectoryOrCreate
      - name: sec-config
        configMap:
          name: os-config
          items:
          - key: config.yml
            path: config.yml
      imagePullSecrets:
      - name: registry-secret
---