---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
  namespace: {{ .Values.global.meta_namespace }}
  labels:
    app-name: opensearch
spec:
  selector:
    app-name: opensearch
  type: ClusterIP
  ports:
  - name: opensearch-api
    port: 9200
    targetPort: 9200
    protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: opensearch-ingress
  namespace: {{ .Values.global.meta_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,kube-system-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /opensearch
        backend:
          serviceName: opensearch-service
          servicePort: opensearch-api
---