---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
  namespace: {{ .Values.global.meta_namespace }}
  labels:
    app-name: opensearch
spec:
  selector:
    app-name: opensearch
  type: ClusterIP
  ports:
  - name: os-api
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: os-pa
    port: 9600
    targetPort: 9600
    protocol: TCP
---
