---
- hosts: localhost
  gather_facts: no
  vars:
    - target: "{{ target_host }}"
      default: "10.128.128.218"

  tasks:
    - add_host:
        name: "{{ target }}"
        groups: os_server

- name: Copy algorithm chart to isolated environment
  hosts: os_server
  strategy: free
  remote_user: "{{ remote_username }}"
  vars:
    #TODO: change hardcoded
    ansible_ssh_private_key_file: ~/.ssh/tfda_iso
  # TODO: data could be in any or multiple instances
  tasks:    
    - name: Copy algorithm file/s
      copy:
        src: "{{ algorithm_files_path }}/"
        dest: "/home/ubuntu/algorithm_files"

    - name: Copy user selected bucket to Iso
      copy:
        src: "{{ user_selected_data }}"
        # the input data path will be /home/ubuntu/<USER_SELECTED_BUCKET>
        dest: "/home/ubuntu"
        directory_mode: yes

    - name: Copy user shell script to Iso
      copy:
        src: "{{ user_input_commands_path }}"
        dest: "/home/ubuntu"
        # directory_mode: yes
        