---
dependencies:
  - name: prometheus-chart
    version: 0.0.0
    repository: file://../../../../services/monitoring/prometheus/prometheus-chart
  - name: alertmanager-chart
    version: 0.0.0
    repository: file://../../../../services/monitoring/alert-manager/alertmanager-chart
  - name: grafana-chart
    version: 0.0.0
    repository: file://../../../../services/monitoring/grafana/grafana-chart
  - name: kube-state-metrics-chart
    version: 0.0.0
    repository: file://../../../../services/monitoring/kube_state_metrics/kube-state-metrics-chart
  - name: node-exporter-chart
    version: 0.0.0
    repository: file://../../../../services/monitoring/node-exporter/node-exporter-chart
