---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: "{{ .Values.global.services_namespace }}"

  labels:
    app-name: alertmanager
spec:
  selector:
    app-name: alertmanager
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: alertmanager-ingress
  namespace: "{{ .Values.global.services_namespace }}"

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: {{  .Values.global.admin_namespace  }}-errorpages@kubernetescrd,{{  .Values.global.services_namespace  }}-strip-prefix@kubernetescrd
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /{{ .Values.global.instance_uid }}/alert
        pathType: ImplementationSpecific
        backend:
          service:
            name: alertmanager-service
            port:
              number: 9093
---