# Copy me and only adapt values.yaml and Chart.yaml!
apiVersion: batch/v1
kind: Job
metadata:
  name: remove-{{ .Values.global.image }}
  namespace: default
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      containers:
      - name: "remove-{{ .Values.global.image }}"
        image: "{{- if .Values.global.custom_registry_url }}{{ .Values.global.custom_registry_url }}{{- else}}{{ .Values.global.registry_url }}{{- end }}/{{ .Values.global.image }}:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: ACTION
          value: "remove"
        - name: SYSTEM_NAMESPACE
          value: "{{ .Values.global.system_namespace }}"
        - name: SERVICES_NAMESPACE
          value: "{{ .Values.global.services_namespace }}"
        volumeMounts:
        - name: data
          mountPath: "/workflows"
      securityContext:
        runAsUser: 0
      volumes:
      - name: data
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/workflows
          type: DirectoryOrCreate
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0