# Copy me and only adapt values.yaml and Chart.yaml!
{{- if eq .Values.global.action "prefetch" }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prefetch-{{ .Values.global.image }}
  namespace: "{{ .Values.global.helm_namespace }}"
spec:
  selector:
    matchLabels:
      app-name: prefetch-{{ .Values.global.image }}-{{ .Values.global.version }}
  template:
    metadata:
      labels:
        app-name: prefetch-{{ .Values.global.image }}-{{ .Values.global.version }}
    spec:
      initContainers:
        - name: init
          image: "{{ .Values.global.registry_url }}/service-checker:{{ .Values.global.kaapana_build_version  }}"
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: WAIT
              value: "kube-helm,kube-helm-service.{{  .Values.global.admin_namespace  }}.svc,5000,/health-check"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: prefetch-{{ .Values.global.image }}
        image: "{{- if .Values.global.custom_registry_url }}{{ .Values.global.custom_registry_url }}{{- else}}{{ .Values.global.registry_url }}{{- end }}/{{ .Values.global.image }}:{{ .Values.global.kaapana_build_version  }}"
        env:
          - name: ACTION
            value: {{ .Values.global.action }}
          - name: ADMIN_NAMESPACE
            value: "{{ .Values.global.admin_namespace }}"
          - name: SERVICES_NAMESPACE
            value: "{{ .Values.global.services_namespace }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
      imagePullSecrets:
        - name: registry-secret
{{- else }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.image }}
  namespace: "{{ .Values.global.helm_namespace }}"
spec:
  template:
    spec:
      initContainers:
        - name: init
          image: "{{ .Values.global.registry_url }}/service-checker:{{ .Values.global.kaapana_build_version  }}"
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: WAIT
              value: "kube-helm,kube-helm-service.{{  .Values.global.admin_namespace  }}.svc,5000,/health-check"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: copy-{{ .Values.global.image }}
        image: "{{- if .Values.global.custom_registry_url }}{{ .Values.global.custom_registry_url }}{{- else}}{{ .Values.global.registry_url }}{{- end }}/{{ .Values.global.image }}:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_jobs }}
        env:
        - name: ACTION
          value: "{{ .Values.global.action }}"
        - name: ADMIN_NAMESPACE
          value: "{{ .Values.global.admin_namespace }}"
        - name: SERVICES_NAMESPACE
          value: "{{ .Values.global.services_namespace }}"
        volumeMounts:
        - name: data
          mountPath: "/workflows"
      # securityContext:
      #   runAsUser: 0
      volumes:
      - name: data
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/workflows
          type: DirectoryOrCreate
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0
{{- end }}