kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: "kub-system-{{  .Values.global.instance_id  }}"
  name: kube-helm-role
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: "kub-system-{{  .Values.global.instance_id  }}"
subjects:
- kind: User
  name: kube-helm-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kube-helm-role
  apiGroup: rbac.authorization.k8s.io