apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: "{{ .Values.global.system_namespace  }}"
spec:
  limits:
  - default:
      # cpu: {{ .Values.global.default_system_limits_cpu }}
      memory: {{ .Values.global.default_system_limits_mem }}
    defaultRequest:
      # cpu: {{ .Values.global.default_system_requests_cpu }}
      memory: {{ .Values.global.default_system_requests_mem }}
    type: Container
---
