kind: Service
apiVersion: v1
metadata:
  name: doccano-frontend-service
  namespace: "{{ .Values.global.extensions_namespace }}"
spec:
  selector:
    app-name: doccano-frontend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: doccano-frontend-ing
  namespace: "{{ .Values.global.extensions_namespace }}"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: {{  .Values.global.admin_namespace  }}-errorpages@kubernetescrd
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /{{ .Values.global.instance_uid }}/doccano/
        pathType: ImplementationSpecific
        backend:
          service:
            name: doccano-frontend-service
            port:
              number: 8080
---