---
kind: Service
apiVersion: v1
metadata:
  name: debug-service
  namespace: "kaapana-system-{{  .Values.global.instance_id  }}"
spec:
  selector:
    app-name: debug-container
  ports:
    - protocol: TCP
      port: 5000
      targetPort: debug-http
      name: log-http-port
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: debug-ingress-ip
  namespace: "kaapana-system-{{  .Values.global.instance_id  }}"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /debug
        pathType: ImplementationSpecific
        backend:
          service:
            name: debug-service
            port:
              name: log-http-port
---

