http_proxy: ""
default_registry: "registry.hzdr.de/jonas.scherer/kaapana"
# default_container_registry: "registry.hzdr.de/kaapana/kaapana"
# default_container_registry: "dktk-jip-registry.dkfz.de/kaapana"
# default_container_registry: "registry.hzdr.de/kaapana/racoon"
#default_container_registry: "registry.hzdr.de/kaapana/kaapana-dev"
container_engine: "docker" # docker or podman
log_level: "INFO" # DEBUG, INFO, WARN or ERROR
build_only: false
platform_filter: "" # comma sperated platform-chart-names
external_source_dirs: "/home/jonas/projects/racoon-repo" # comma sperated paths 
exit_on_error: false
disable_linting: false
