http_proxy: ""
default_container_registry: "registry.hzdr.de/santhosh.parampottupadam/tfdamvp1"
log_level: "WARN"
build_containers: true
push_containers: true
push_dev_containers_only: false
build_charts: true
push_charts: true
create_package: false