# Copied and adapted from chart-manager-chart
apiVersion: batch/v1
kind: Job
metadata:
  name: remove-kube-helm-helpers
  namespace: default
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      containers:
      - name: remove-kube-helm-helpers
        image: "{{ .Values.global.registry_url }}/kube-helm-helpers:0.1.0"
        imagePullPolicy: Never
        env:
        - name: ACTION
          value: "remove"
        - name: CHARTS_DIR
          value: charts/helpers
        volumeMounts:
        - name: data
          mountPath: /charts
{{- range $collection := .Values.global.kaapana_collections }}
      - name: remove-{{ $collection.name }}
        image: "{{ .Values.global.registry_url }}/{{ $collection.name }}:{{ $collection.version }}"
        imagePullPolicy: Never
        env:
        - name: ACTION
          value: "remove"
        - name: CHARTS_DIR
          value: charts/collections
        volumeMounts:
        - name: data
          mountPath: /charts
{{- end }}
      securityContext:
        runAsUser: 0
      volumes:
      - name: data
        hostPath:
          path: "{{ .Values.global.fast_data_dir }}/charts"
          type: DirectoryOrCreate
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0