
apiVersion: v1
kind: Service
metadata:
  name: kube-helm-service
  namespace: "kub-system-{{  .Values.global.instance_id  }}"
  labels:
    app-name: kube-helm
spec:
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
  selector:
    app-name: kube-helm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-helm-ingress
  namespace: "kub-system-{{  .Values.global.instance_id  }}"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kub-system-{{  .Values.global.instance_id  }}-errorpages@kubernetescrd,kub-system-{{  .Values.global.instance_id  }}-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /kube-helm-api
        pathType: ImplementationSpecific
        backend:
          service:
            name: kube-helm-service
            port:
              number: 5000
---