---
dependencies:
# Namespaces
  - name: extensions-namespace
    version: 0.0.0
    repository: file://deps/extensions-namespace
  - name: jobs-namespace
    version: 0.0.0
    repository: file://deps/jobs-namespace
  - name: services-namespace
    version: 0.0.0
    repository: file://deps/services-namespace
# META
  - name: meta-init-chart
    condition: Release.IsInstall
    version: 0.0.0
    repository: file://../../../services/meta/meta-init/meta-init-chart
  - name: opensearch-chart
    version: 0.0.0
    repository: file://../../../services/meta/opensearch/opensearch-chart
  - name: os-dashboards-chart
    version: 0.0.0
    repository: file://../../../services/meta/os-dashboards/os-dashboards/os-dashboards-chart
# BASE
  - name: landing-page-kaapana-chart
    version: 0.0.0
    repository: file://../../../services/base/landing-page-kaapana/landing-page-kaapana-chart